/*
 * 企业号意向用户管理
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tiktok.sdk.models;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * EnterpriseLeadsLeadsUserInlineResponse200DataTagList
 */

public class EnterpriseLeadsLeadsUserInlineResponse200DataTagList {
  @JsonProperty("tag_id")
  private Integer tagId = null;

  @JsonProperty("tag_name")
  private String tagName = null;

  public EnterpriseLeadsLeadsUserInlineResponse200DataTagList tagId(Integer tagId) {
    this.tagId = tagId;
    return this;
  }

   /**
   * Get tagId
   * @return tagId
  **/
  public Integer getTagId() {
    return tagId;
  }

  public void setTagId(Integer tagId) {
    this.tagId = tagId;
  }

  public EnterpriseLeadsLeadsUserInlineResponse200DataTagList tagName(String tagName) {
    this.tagName = tagName;
    return this;
  }

   /**
   * Get tagName
   * @return tagName
  **/
  public String getTagName() {
    return tagName;
  }

  public void setTagName(String tagName) {
    this.tagName = tagName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnterpriseLeadsLeadsUserInlineResponse200DataTagList inlineResponse200DataTagList = (EnterpriseLeadsLeadsUserInlineResponse200DataTagList) o;
    return Objects.equals(this.tagId, inlineResponse200DataTagList.tagId) &&
        Objects.equals(this.tagName, inlineResponse200DataTagList.tagName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tagId, tagName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnterpriseLeadsLeadsUserInlineResponse200DataTagList {\n");
    
    sb.append("    tagId: ").append(toIndentedString(tagId)).append("\n");
    sb.append("    tagName: ").append(toIndentedString(tagName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
