/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tiktok.sdk.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import java.util.Objects;

/**
 * ExternalDataItemExternalDataItemExternalItemLike
 */

@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
public class ExternalDataItemExternalDataItemExternalItemLike {
  @JsonProperty("date")
  private String date = null;

  @JsonProperty("like")
  private Integer like = null;

  public ExternalDataItemExternalDataItemExternalItemLike date(String date) {
    this.date = date;
    return this;
  }

   /**
   * 日期
   * @return date
  **/
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public ExternalDataItemExternalDataItemExternalItemLike like(Integer like) {
    this.like = like;
    return this;
  }

   /**
   * 每日点赞数
   * @return like
  **/
  public Integer getLike() {
    return like;
  }

  public void setLike(Integer like) {
    this.like = like;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalDataItemExternalDataItemExternalItemLike externalItemLike = (ExternalDataItemExternalDataItemExternalItemLike) o;
    return Objects.equals(this.date, externalItemLike.date) &&
        Objects.equals(this.like, externalItemLike.like);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, like);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalDataItemExternalDataItemExternalItemLike {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    like: ").append(toIndentedString(like)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
