/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tiktok.sdk.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ExternalDataItemExternalDataItemInlineResponse2004Data
 */

@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
public class ExternalDataItemExternalDataItemInlineResponse2004Data {
  @JsonProperty("error_code")
  private Integer errorCode = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("result_list")
  private List<ExternalDataItemExternalDataItemExternalItemShare> resultList = null;

  public ExternalDataItemExternalDataItemInlineResponse2004Data errorCode(Integer errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  public Integer getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(Integer errorCode) {
    this.errorCode = errorCode;
  }

  public ExternalDataItemExternalDataItemInlineResponse2004Data description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ExternalDataItemExternalDataItemInlineResponse2004Data resultList(List<ExternalDataItemExternalDataItemExternalItemShare> resultList) {
    this.resultList = resultList;
    return this;
  }

  public ExternalDataItemExternalDataItemInlineResponse2004Data addResultListItem(ExternalDataItemExternalDataItemExternalItemShare resultListItem) {
    if (this.resultList == null) {
      this.resultList = new ArrayList<>();
    }
    this.resultList.add(resultListItem);
    return this;
  }

   /**
   * Get resultList
   * @return resultList
  **/
  public List<ExternalDataItemExternalDataItemExternalItemShare> getResultList() {
    return resultList;
  }

  public void setResultList(List<ExternalDataItemExternalDataItemExternalItemShare> resultList) {
    this.resultList = resultList;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalDataItemExternalDataItemInlineResponse2004Data inlineResponse2004Data = (ExternalDataItemExternalDataItemInlineResponse2004Data) o;
    return Objects.equals(this.errorCode, inlineResponse2004Data.errorCode) &&
        Objects.equals(this.description, inlineResponse2004Data.description) &&
        Objects.equals(this.resultList, inlineResponse2004Data.resultList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorCode, description, resultList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalDataItemExternalDataItemInlineResponse2004Data {\n");
    
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    resultList: ").append(toIndentedString(resultList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
